config/routes.rb
Rails.application.routes.draw do
  

  get 'about', to: 'pages#about'
  get 'list', to: 'pages#list'

  devise_for :users, path: '', path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :logs

  root to: 'pages#home'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  mount_uploader :cover, CoverUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, 
                  if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @logs = Log.all
  end

  def show
  end

  def new
    @log = Log.new
  end

  def edit
  end

  def create
    @log = Log.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
    end
  end

  private
    def set_log
      @log = Log.find(params[:id])
    end

    def log_params
      params.require(:log).permit(:name, :artists, :venue, :cover)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def list
    @logs = Log.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aya | Concert Log</title>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Rambla" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/application_nav" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/logs/_form.html.erb
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :log_name %>
  </div>

  <div class="field">
    <%= form.label :artists %>
    <%= form.text_field :artists, id: :log_artists %>
  </div>

  <div class="field">
    <%= form.label :cover %>
    <%= form.file_field :cover %>
  </div>

  <div class="field">
    <%= form.label :venue %>
    <%= form.text_area :venue, id: :log_venue %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/edit.html.erb
<h1>Editing Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concert Log</h1>
<h3>details</h3>

<hr><br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artists</th>
      <th>Venue</th>
      <th colspan="3"><%= "Actions" if logged_in?(:site_admin) %></th>
    </tr>
  </thead>

  <tbody>
    <% @logs.each do |log| %>
      <tr>
        <td><%= log.name %></td>
        <td><%= log.artists %></td>
        <td><%= log.venue %></td>
        <td><%= link_to 'Details', log %></td>
        <td><%= link_to 'Edit', edit_log_path(log) if logged_in?(:site_admin) %></td>
        <td><%= link_to 'Delete', log, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'Create New Log', new_log_path if logged_in?(:site_admin)%></p>

app/views/logs/new.html.erb
<h1>New Log</h1>

<%= render 'form', log: @log %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= image_tag @log.cover.url if @log.cover? %>
  </div>
  <div class="col-sm-9">
    <p>
      <strong>Name:</strong>
      <%= @log.name %>
    </p>

    <p>
      <strong>Artists:</strong>
      <%= @log.artists %>
    </p>

    <p>
      <strong>Venue:</strong>
      <%= @log.venue %>
    </p>

    <%= link_to 'Edit | ', edit_log_path(@log) if logged_in?(:site_admin)%>
    <%= link_to 'Back', logs_path %>
  </div>
</div>

app/views/pages/about.html.erb
<h1>About</h1>
<h3>my concert log</h3>

<hr><br>

<p>My name is Aya. I like going to concerts. Here you will find a log of all the concerts I have been to. Edit and create logs to keep it updated.</p>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<h3>to my concert log</h3>



<hr><br>
Site requirements:
<ul>
<li><strike>build a rails app with postgresql</strike></li>
<li><strike>create CRUD for blogs/posts</strike></li>
<li><strike>install devise</strike></li>
<li><strike>install petergate</strike></li>
<li><strike>install bootstrap</strike></li>
<li><strike>make it so users can only visit the home page without registering or signing in</strike></li>
<li><strike>a signed in users should only be able to read blogs/posts</strike></li>
<li><strike>setup an admin who can edit/create/and delete blogs/posts</strike></li>
<li><strike>create a nav bar</strike></li>
<li><strike>store it in a partial and render it in the layout file</strike></li>
<li><strike>use bootstrap to style the nav-bar</strike></li>
<li><strike>use google fonts to further customization</strike></li>
<li><strike>implement an image link in the nav-bar</strike></li>
</ul>

<% if !current_user %>
  <p>Please <%= link_to "sign in", new_user_session_path %> to see the rest of the site! </p>
<% end %>

app/views/pages/list.html.erb
<p id="notice"><%= notice %></p>

<h1>List of Concerts</h1>
<h3>in my concert log</h3>

<hr><br>

<% @logs.each do |log| %>
  <p><%= log.name %> <%= link_to 'Details', log %></p>
<% end %>

app/views/shared/_application_nav.html.erb
    <nav class="navbar navbar-expand-md nav-bar">
        <div class="container">
            <div class="col-sm-1">
                <%= link_to image_tag("try.png"), root_path, class: 'navbar-brand' %>
            </div>
            <div class="col-sm-11 nav navbar-nav navbar-right">
                <%= link_to "  ", root_path %>
                <%= link_to "Home", root_path %>
                <%= link_to "About", about_path if current_user %>
                <%= link_to "List", list_path if current_user %>
                <%= link_to "Concert Log", logs_path if current_user %>
                <% if current_user %>
                  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                <% else %>
                  <%= link_to "Sign in", new_user_session_path %>
                <% end %>
            </div>
        </div>
    </nav> 